### ISSUE TITLE
Edge Opens with random amount of tabs

### ISSUE THREAD

**Issue by Craig939393** [karma-runner/karma-edge-launcher#3]
On Windows 10 using latest packages for karma and launchers, edge is the only browser that launches with multiple tabs running tests, although it seems that my console only knows one exists and closes Edge once thats finished.

P.S. thanks for providing

**Comment by nickserv** [comment]
This seems to be the same issue as #4. I'll merge these issues, but let me know if it's unrelated (if the number of tabs opened isn't equivalent to the number of tabs you previously had open plus one).

**Comment by Craig939393** [comment]
I was under the impression that only one tab would open as thats what other browsers do.

To be specific, the issue I was facing here was that it running the launcher continuously opened new tabs, until the first tab it opened finished running all the tests, in which case everything stopped as expected. This meant that I seemed to have many many tabs running the same tests in parallel (if thats even possible.)

**Comment by nickserv** [comment]
The behavior I observed recently is that using the launcher with singleRun will start Edge with a tab tab and close it when the tests complete, but rerunning a test suite will restart the browser keeping the last tab.

This leads to an extra tab every test run, which isn't ideal. Is that what you're seeing? I believe only the last tab should have the actual Karma UI running though, the rest would be old results.

**Comment by Craig939393** [comment]
Yeah thats probably what I was seeing then

**Comment by nickserv** [comment]
Cool, please track #4 and let me know if you discover anything else or have any ideas. I'm experimenting with alternate ways to launch edge and if it's possible to kill it without the Edge tab.
