### ISSUE TITLE
Publish 0.4.3 on npm

### ISSUE THREAD

**Issue by TheOzim** [karma-runner/karma-edge-launcher#8]
I just noticed that the current version 0.4.3 is not available on npm (latest is 0.4.2). It would be helpful to have the fix for #4 available via npm as well.

Would it be possible to publish 0.4.3 on npm?

**Comment by watilde** [comment]
@zzo @nickmccurdy I agreed on this issue. Can I help here to maintain this package?

**Comment by johnjbarton** [comment]
I added @watilde to the github project.  FYI:
```
$ npm owner ls karma-edge-launcher
nickmccurdy <nick@nickmccurdy.com>
watilde <daijiro.wachi@gmail.com>
```

**Comment by watilde** [comment]
Thank you @johnjbarton! I'm going to ship the latest version then.

**Comment by watilde** [comment]
Oh wait... This was a reason why it was not published yet.
https://github.com/karma-runner/karma-edge-launcher/pull/6#issuecomment-423006648
